baseURL: 'https://zenuas.github.io/phaser3-training/'
languageCode: 'ja'
title: 'Phaser 3練習'
uglyurls: true
enableGitInfo: true

params:
  author: "zenuas"
  description: "Phaser 3練習リポジトリ"
  keywords: "Phaser 3,hugo"
  
  github:
    owner_name: "zenuas"
    owner_url: "https://github.com/zenuas"
    repository_url: "https://github.com/zenuas/phaser3-training"
    repository_nwo: "zenuas/phaser3-training"
    source:
      branch: "master"
    license:
      name: "MIT License"

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
    parser:
      attribute:
        block: true

taxonomies:
  # nothing
